// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3vggCfCmm9cC6OWVXz7_X8GuEqRaaJMg',
    appId: '1:161643875416:web:5891fbf0e3cc7b67a94e2d',
    messagingSenderId: '161643875416',
    projectId: 'kan-q-d0dd2',
    authDomain: 'kan-q-d0dd2.firebaseapp.com',
    storageBucket: 'kan-q-d0dd2.appspot.com',
    measurementId: 'G-EDDKLVW6MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHcbXr8tsrUjwprXPhuZ2tWVOlbnEt1Sw',
    appId: '1:161643875416:android:607fe610b9063f44a94e2d',
    messagingSenderId: '161643875416',
    projectId: 'kan-q-d0dd2',
    storageBucket: 'kan-q-d0dd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc7t6oh_1_VWvDiv8A0M1nYdFctZwCdWw',
    appId: '1:161643875416:ios:e0a451757e2f50f8a94e2d',
    messagingSenderId: '161643875416',
    projectId: 'kan-q-d0dd2',
    storageBucket: 'kan-q-d0dd2.appspot.com',
    iosClientId: '161643875416-uehos7b5pq1qs3iep1r2ri32jnkqj738.apps.googleusercontent.com',
    iosBundleId: 'com.mahdiabbasi.kanq.kanq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc7t6oh_1_VWvDiv8A0M1nYdFctZwCdWw',
    appId: '1:161643875416:ios:e0a451757e2f50f8a94e2d',
    messagingSenderId: '161643875416',
    projectId: 'kan-q-d0dd2',
    storageBucket: 'kan-q-d0dd2.appspot.com',
    iosClientId: '161643875416-uehos7b5pq1qs3iep1r2ri32jnkqj738.apps.googleusercontent.com',
    iosBundleId: 'com.mahdiabbasi.kanq.kanq',
  );
}
